apiVersion: v1
kind: Pod
metadata:
  labels:
    app: omgwtfssl
  name: omgwtfssl
spec:
  restartPolicy: Never
  containers:
  - env:
    - name: SSL_SUBJECT
      value: <my-server-name>
    - name: CA_SUBJECT
      value: <my-email>
    - name: SSL_KEY
      value: /certs/<my-server-name>.key
    - name: SSL_CSR
      value: /certs/<my-server-name>.csr
    - name: SSL_CERT
      value: /certs/<my-server-name>.crt
    name: omgwtfssl
    image: paulczar/omgwtfssl
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: certs
      name: certs
  volumes:
    - name: certs
      hostPath:
        path: "/home/<someFolderLocation>/certs-pv"
