apiVersion: v1
kind: Pod
metadata:
  labels:
    app: omgwtfssl
  name: omgwtfssl
spec:
  restartPolicy: Never
  containers:
  - env:
    - name: SSL_SUBJECT
      value: 10.0.2.15
    - name: CA_SUBJECT
      value: a.tregubova@list.ru
    - name: SSL_KEY
      value: /certs/10.0.2.15.key
    - name: SSL_CSR
      value: /certs/10.0.2.15.csr
    - name: SSL_CERT
      value: /certs/10.0.2.15.crt
    name: omgwtfssl
    image: paulczar/omgwtfssl
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: certs
      name: certs
  volumes:
    - name: certs
      hostPath:
        path: "/home/anastasia/nc-deployment/certs-pv"
